### ISSUE TITLE
Not an issue.. Just a question...

### ISSUE THREAD

**Issue by veerjainATgmail** [BharathRavi27/react-twitter-ui-clone#2]
Hey, The FE Looks really good.

wondering if you considered using any of the ui libraries like
react styled-components, styled-ui for styling? 
It will make code reading much much better.
Good luck.

**Comment by BharathRavi27** [comment]
@veerjainATgmail I haven't used any third party UI libraries here. 
I encourage you to add features and submit PR

**Comment by veerjainATgmail** [comment]
@BharathRavi27 , sure. 👍
